apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/tienda-microservices-476518/image-registry/client-gateway
        name: client-gateway
        resources: {}
status: {}
